# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: artifactbundle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        swift-version: [ "5.7", "5.6.1" ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: swiftty/swiftpm-artifactbundle-builder@main
      id: builder
      with:
        swift-version: ${{ matrix.swift-version }}

  bundle:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
    - uses: swiftty/swiftpm-artifactbundle-bundler@main
      id: bundler
      with:
        variants-version: '0.0.1'
    - uses: actions/upload-artifact@v3
      with:
        name: artifactbundle
        path: '${{ steps.bundler.outputs.path }}/**/*.artifactbundle.zip'
        retention-days: 1
